const dataInfo = `
[
    {
        "id": 1,
        "src": "/img/1.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "red",
        "size": "XL",
        "maxQuantity": 2
    },
    {
        "id": 2,
        "src": "/img/2.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "black",
        "size": "XS",
        "maxQuantity": 3
    },
    {
        "id": 3,
        "src": "/img/3.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "blue",
        "size": "L",
        "maxQuantity": 1
    },
    {
        "id": 4,
        "src": "/img/4.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "red",
        "size": "XL",
        "maxQuantity": 2
    },
    {
        "id": 5,
        "src": "/img/5.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "black",
        "size": "XS",
        "maxQuantity": 5
    },
    {
        "id": 6,
        "src": "/img/6.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "blue",
        "size": "L",
        "maxQuantity": 6
    },
    {
        "id": 7,
        "src": "/img/1.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "red",
        "size": "XL",
        "maxQuantity": 2
    },
    {
        "id": 8,
        "src": "/img/2.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "blue",
        "size": "L",
        "maxQuantity": 3
    },
    {
        "id": 9,
        "src": "/img/3.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "black",
        "size": "XS",
        "maxQuantity": 2
    },
    {
        "id": 10,
        "src": "/img/4.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "orange",
        "size": "M",
        "maxQuantity": 1
    },
    {
        "id": 11,
        "src": "/img/5.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "red",
        "size": "S",
        "maxQuantity": 6
    },
    {
        "id": 12,
        "src": "/img/1.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "green",
        "size": "ML",
        "maxQuantity": 8
    },
    {
        "id": 13,
        "src": "/img/2.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "black",
        "size": "XS",
        "maxQuantity": 6
    },
    {
        "id": 14,
        "src": "/img/3.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "blue",
        "size": "L",
        "maxQuantity": 1
    },
    {
        "id": 15,
        "src": "/img/1.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "red",
        "size": "XL",
        "maxQuantity": 2
    },
    {
        "id": 16,
        "src": "/img/2.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "blue",
        "size": "L",
        "maxQuantity": 3
    },
    {
        "id": 17,
        "src": "/img/3.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "black",
        "size": "XS",
        "maxQuantity": 2
    },
    {
        "id": 18,
        "src": "/img/4.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "orange",
        "size": "M",
        "maxQuantity": 1
    },
    {
        "id": 19,
        "src": "/img/5.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "red",
        "size": "S",
        "maxQuantity": 6
    },
    {
        "id": 20,
        "src": "/img/1.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "green",
        "size": "ML",
        "maxQuantity": 8
    },
    {
        "id": 21,
        "src": "/img/2.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "black",
        "size": "XS",
        "maxQuantity": 6
    },
    {
        "id": 22,
        "src": "/img/3.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52.00",
        "width": 360,
        "height": 420,
        "widthCart": 262,
        "heightCart": 306,
        "color": "blue",
        "size": "L",
        "maxQuantity": 1
    }
]
`

